### ISSUE TITLE
Compile failure path for type 'com.gwidgets.api.client.GwtyLeaflet

### ISSUE THREAD

**Issue by dasurid** [gwidgets/gwty-leaflet#1] opened 2016-07-13 02:47 UTC
I compiled gwty-leaflet to a jar file using maven and then added that jar to the build path of a simple test project that I created (with Eclipse).   The project is using GWT 2.8.0.beta1 and is the standard GWT "greet".   The project works fine until I add an inherits for GwtyLeaflet.

After adding an <inherits name='com.gwidgets.api.GwtyLeaflet' /> element to the app's gwt.xml file the following error is displayed at compile time... 

Do you have any suggestion as to what the problem could be? The jar is on the build path, as is gwt-material-1.5.3.jar, gwt-material-addins-1.5.2.jar and gwt-material-themes-1.5.2.jar.

> Finding entry point classes
      Tracing compile failure path for type 'com.gwidgets.api.client.GwtyLeaflet'
         Checked 0 dependencies for errors.
      [ERROR] Hint: Check that the type name 'com.gwidgets.api.client.GwtyLeaflet' is really what you meant
      [ERROR] Hint: Check that your classpath includes all required source roots

**Comment by zak905** [comment] 2016-07-13 08:19
Hi dasurid, 

some other users complained about this, I am trying to reproduce the error.

**Comment by dasurid** [comment] 2016-07-13 13:41
Thank you for looking into it. Your wrapper looks very interesting.  

Having just worked on a Vaadin Polymer based project, I appreciate JsInterop very much, it could be a game changer for GWT.

**Comment by zak905** [comment] 2016-07-20 12:48
The issue is fixed now. You can use version 0.2, which fixed the issue:

                       <dependency>
                        <groupId>com.gwidgets</groupId>
                        <artifactId>gwty-leaflet</artifactId>
                        <version>0.2</version>
                     </dependency>

**Comment by zak905** [comment] 2016-07-21 20:08
Can I close this issue ?

**Comment by dasurid** [comment] 2016-07-22 00:25
Yes. Thanks very much.

**Closed** 2016-07-22 09:08 UTC
